### ISSUE TITLE
Sorry for posting that on issues, but.. 

### ISSUE THREAD

**Issue by BlockBoy** [iPocket/PocketBot#1]
I want to talk to you. Do you know pocketmine api?  (I think so, because you are on ImagicalMine github.)
I will tell you more if you want.

**Comment by iPocket** [comment]
Yes. :)

**Comment by iPocket** [comment]
If you want to talk to me, Get gitter.
https://gitter.im

**Comment by BlockBoy** [comment]
Please check your gitter
